import { jsPDF } from "jspdf";

export interface ExportData {
  title: string;
  subtitle?: string;
  content: string; // Plain text or JSON string depending on tool
  metadata?: any;
}

export function exportToTXT(filename: string, content: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".txt") ? filename : `${filename}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportToCSV(filename: string, rows: string[][]) {
  const csvContent = rows.map(e => e.map(val => `"${val.replace(/"/g, '""')}"`).join(",")).join("\n");
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".csv") ? filename : `${filename}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportToDOCX(filename: string, title: string, content: string) {
  // Creating a robust Rich HTML document that Word processes beautifully
  const html = `
    <html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
    <head>
      <meta charset="utf-8">
      <title>${title}</title>
      <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; line-height: 1.6; margin: 1in; color: #333333; }
        h1 { color: #111111; font-size: 24pt; border-bottom: 1px solid #cccccc; padding-bottom: 6px; }
        h2 { color: #7C3AED; font-size: 16pt; margin-top: 18pt; }
        p { font-size: 11pt; margin-bottom: 10pt; }
        ul { margin-bottom: 10pt; }
        li { font-size: 11pt; margin-bottom: 4pt; }
        .footer { font-size: 9pt; color: #777777; text-align: center; margin-top: 50pt; }
      </style>
    </head>
    <body>
      <h1>${title}</h1>
      <div class="content">
        ${content.replace(/\n/g, "<br/>")}
      </div>
      <div class="footer">Generated by AI Toolbox Pro</div>
    </body>
    </html>
  `;
  const blob = new Blob([html], { type: "application/msword" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".docx") ? filename : `${filename}.docx`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportToPDF(filename: string, title: string, rawContent: string, isResume: boolean = false) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4"
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;

  // Modern Dark/Light Accent Header
  doc.setFillColor(11, 11, 11);
  doc.rect(0, 0, pageWidth, 40, "F");

  // Accent Line
  doc.setFillColor(0, 191, 255);
  doc.rect(0, 40, pageWidth, 1.5, "F");

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(22);
  doc.text(title, margin, 25);

  // Subtitle
  doc.setFont("Helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(200, 200, 200);
  doc.text("AI TOOLBOX PRO - SaaS PLATFORM EXPORT", margin, 32);

  // Body content
  doc.setTextColor(51, 51, 51);
  doc.setFontSize(11);

  let currentY = 55;

  if (isResume) {
    try {
      const data = JSON.parse(rawContent);
      // Resume specific gorgeous formatting
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(16);
      doc.setTextColor(11, 11, 11);
      doc.text(data.name || "Full Name", margin, currentY);
      currentY += 6;

      doc.setFont("Helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text(`${data.email || ""}   |   ${data.phone || ""}`, margin, currentY);
      currentY += 10;

      // Divider
      doc.setDrawColor(230, 230, 230);
      doc.line(margin, currentY, margin + contentWidth, currentY);
      currentY += 8;

      // Professional Summary
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(124, 58, 237); // Purple accent
      doc.text("PROFESSIONAL SUMMARY", margin, currentY);
      currentY += 6;

      doc.setFont("Helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(51, 51, 51);
      const summaryLines = doc.splitTextToSize(data.summary || "", contentWidth);
      doc.text(summaryLines, margin, currentY);
      currentY += summaryLines.length * 5 + 6;

      // Professional Experience
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(124, 58, 237);
      doc.text("PROFESSIONAL EXPERIENCE", margin, currentY);
      currentY += 6;

      doc.setFont("Helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(51, 51, 51);
      const expLines = doc.splitTextToSize(data.experience || "", contentWidth);
      doc.text(expLines, margin, currentY);
      currentY += expLines.length * 5 + 6;

      // Core Skills
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(124, 58, 237);
      doc.text("CORE SKILLS", margin, currentY);
      currentY += 6;

      doc.setFont("Helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(51, 51, 51);
      const skillsLines = doc.splitTextToSize(data.skills || "", contentWidth);
      doc.text(skillsLines, margin, currentY);
    } catch (e) {
      // Fallback to standard flow
      isResume = false;
    }
  }

  if (!isResume) {
    // Normal text lines
    const splitLines = doc.splitTextToSize(rawContent, contentWidth);
    let linesPerPage = Math.floor((pageHeight - margin - currentY) / 6);

    let lineIndex = 0;
    while (lineIndex < splitLines.length) {
      if (currentY > pageHeight - margin) {
        doc.addPage();
        currentY = 25; // Reset Y on new page
      }
      doc.text(splitLines[lineIndex], margin, currentY);
      currentY += 6;
      lineIndex++;
    }
  }

  // Footer on current page
  doc.setFont("Helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Downloaded from AI Toolbox Pro (https://ai.studio/build)", margin, pageHeight - 10);

  doc.save(filename.endsWith(".pdf") ? filename : `${filename}.pdf`);
}

export function exportCanvasAsImage(canvas: HTMLCanvasElement, filename: string, format: "png" | "jpg" | "webp" = "png") {
  const mimeType = format === "png" ? "image/png" : format === "jpg" ? "image/jpeg" : "image/webp";
  const url = canvas.toDataURL(mimeType, 1.0);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(`.${format}`) ? filename : `${filename}.${format}`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
}
